//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadatakEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka
    {
        public int IDStavka { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> ServiceVehicleID { get; set; }
    
        public virtual ServiceVehicle ServiceVehicle { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
